# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH

MYSQLVARS="\-e MYSQL_USER=user1 -e MYSQL_PASSWORD=mypa55 -e MYSQL_DATABASE=items -e MYSQUL_ROOT_PASSWORD=r00tpa55"
MYSQLIMG=rhscl/mysql-57-rhel7
export MYSQLVARS MYSQLIMG

GITTOKEN=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
export GITTOKEN

MAPI=https://api.na45.prod.nextcle.com:6443
WDOM=apps.na45.prod.nextcle.com
NEXUSSRVR=nexus-common.apps.na45.prod.nextcle.com
DUSER=mrcihj
DPASSWD=fd2a2d78bee441a18a77
GUSER=lizalbers-github
QUSER=lalbers
export MAPI WDOM NEXUSSVR DUSER DPASSWD GUSER QUSER


# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions


alias loginoc="oc login -u mrcihj -p fd2a2d78bee441a18a77 https://api.na45.prod.nextcle.com:6443"
alias logoutoc="oc logout"
alias psnames='echo podman ps --format \"{{.ID}} -- {{.Names}} -- {{.Image}}\"'
alias psstatus='echo podman ps --format \"{{.ID}} -- {{.Names}} -- {{.Status}}\"'
alias psports='echo podman ps --format \"{{.ID}} -- {{.Names}} -- {{.Ports}}\"'
alias sourcelabenv='source /usr/local/etc/ocp4.config'
alias catlabenv='cat /usr/local/etc/ocp4.config'
